export const speakers = [
  {
    firstName: "Paulus",
    lastName: "Schoutsen",
    role: "President of the OHF",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 1,
    theme: "dark",
  },
  {
    firstName: "Franck",
    lastName: "Nijhof",
    role: "Lead of Home Assistant",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 2,
    theme: "dark",
  },
  {
    firstName: "Jean-Loïc",
    lastName: "Pouffier",
    role: "Lead of Product & UX",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 3,
    theme: "dark",
  },
  {
    firstName: "Marcel",
    lastName: "van der Veldt",
    role: "Lead of Ecosystem",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 4,
    theme: "light",
  },
  {
    firstName: "TBC",
    lastName: "tbc",
    role: "TBC",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 5,
    theme: "dark",
  },
  {
    firstName: "Carl",
    lastName: "Olof Albertsson",
    role: "VP of commercial at Nabu Casa",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 6,
    theme: "light",
  },
  {
    firstName: "Trevor",
    lastName: "Schirmer",
    role: "Technical Lead at Apollo",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 7,
    theme: "light",
  },
  {
    firstName: "Laura",
    lastName: "Palombi",
    role: "Product Manager at OHf",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 8,
    theme: "dark",
  },
  {
    firstName: "Matthias",
    lastName: "de Baat",
    role: "UX Designer at OHf",
    image: "/images/speaker-cards/speaker-card-1.webp",
    variant: 8,
    theme: "dark",
  },
];
